apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: registry.gitlab.com/robinmccorkell/natlb
    newTag: "0.1.1"

commonLabels:
  app: natlb

resources:
  - deployment.yaml
  - rbac.yaml
