apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: natlb

images:
  - name: registry.gitlab.com/robinmccorkell/k8s-natlb
    newTag: latest

commonLabels:
  app: natlb

resources:
  - deployment.yaml
  - serviceaccount.yaml
  - rbac.yaml

secretGenerator:
  - name: gitlab-registry
    files:
      - .dockerconfigjson
    type: kubernetes.io/dockerconfigjson
