apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: natlb-controller
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: natlb-controller
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: ClusterRole
  name: natlb-controller
  apiGroup: rbac.authorization.k8s.io
